/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import ftl.Blur;
import ftl.FtlPackage;
import ftl.In;
import ftl.Out;
import ftl.Program;
import ftl.Temp;
import ftl.Transform;
import ftl.Video;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == FtlPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case FtlPackage.BLUR:
				sequence_Blur(context, (Blur) semanticObject); 
				return; 
			case FtlPackage.IN:
				sequence_In(context, (In) semanticObject); 
				return; 
			case FtlPackage.OUT:
				sequence_Out(context, (Out) semanticObject); 
				return; 
			case FtlPackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case FtlPackage.TEMP:
				sequence_Temp(context, (Temp) semanticObject); 
				return; 
			case FtlPackage.TRANSFORM:
				sequence_Transform(context, (Transform) semanticObject); 
				return; 
			case FtlPackage.VIDEO:
				sequence_Video(context, (Video) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Instruction returns Blur
	 *     Blur returns Blur
	 *
	 * Constraint:
	 *     radius=INT
	 */
	protected void sequence_Blur(ISerializationContext context, Blur semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FtlPackage.Literals.BLUR__RADIUS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FtlPackage.Literals.BLUR__RADIUS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBlurAccess().getRadiusINTTerminalRuleCall_1_0(), semanticObject.getRadius());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Stream returns In
	 *     In returns In
	 *
	 * Constraint:
	 *     (name=STRING path=STRING)
	 */
	protected void sequence_In(ISerializationContext context, In semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FtlPackage.Literals.STREAM__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FtlPackage.Literals.STREAM__NAME));
			if (transientValues.isValueTransient(semanticObject, FtlPackage.Literals.STREAM__PATH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FtlPackage.Literals.STREAM__PATH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInAccess().getNameSTRINGTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getInAccess().getPathSTRINGTerminalRuleCall_3_0(), semanticObject.getPath());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Stream returns Out
	 *     OutputStream returns Out
	 *     Out returns Out
	 *
	 * Constraint:
	 *     (name=STRING path=STRING)
	 */
	protected void sequence_Out(ISerializationContext context, Out semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FtlPackage.Literals.STREAM__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FtlPackage.Literals.STREAM__NAME));
			if (transientValues.isValueTransient(semanticObject, FtlPackage.Literals.STREAM__PATH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FtlPackage.Literals.STREAM__PATH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOutAccess().getNameSTRINGTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getOutAccess().getPathSTRINGTerminalRuleCall_3_0(), semanticObject.getPath());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     (streams+=Stream* transforms+=Transform*)
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Stream returns Temp
	 *     OutputStream returns Temp
	 *     Temp returns Temp
	 *
	 * Constraint:
	 *     (name=STRING path=STRING)
	 */
	protected void sequence_Temp(ISerializationContext context, Temp semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FtlPackage.Literals.STREAM__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FtlPackage.Literals.STREAM__NAME));
			if (transientValues.isValueTransient(semanticObject, FtlPackage.Literals.STREAM__PATH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FtlPackage.Literals.STREAM__PATH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTempAccess().getNameSTRINGTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getTempAccess().getPathSTRINGTerminalRuleCall_3_0(), semanticObject.getPath());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Transform returns Transform
	 *
	 * Constraint:
	 *     (output=STRING instruction+=Instruction*)
	 */
	protected void sequence_Transform(ISerializationContext context, Transform semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Video returns Video
	 *
	 * Constraint:
	 *     input=STRING
	 */
	protected void sequence_Video(ISerializationContext context, Video semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FtlPackage.Literals.VIDEO__INPUT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FtlPackage.Literals.VIDEO__INPUT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVideoAccess().getInputSTRINGTerminalRuleCall_1_0(), semanticObject.getInput());
		feeder.finish();
	}
	
	
}
