/*
 * generated by Xtext 2.20.0
 */
package org.xtext.ftl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FTLUiModule extends AbstractFTLUiModule {

	public FTLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
