/*
 * generated by Xtext 2.20.0
 */
package org.xtext.ftl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.ftl.FTLRuntimeModule;
import org.xtext.ftl.FTLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FTLIdeSetup extends FTLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FTLRuntimeModule(), new FTLIdeModule()));
	}
	
}
