/*
 * generated by Xtext 2.20.0
 */
package org.xtext.ftl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFTLScopeProvider extends DelegatingScopeProvider {
}
