/*
 * generated by Xtext 2.20.0
 */
package org.xtext.ftl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.ftl.ui.internal.FtlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FTLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(FtlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		FtlActivator activator = FtlActivator.getInstance();
		return activator != null ? activator.getInjector(FtlActivator.ORG_XTEXT_FTL_FTL) : null;
	}

}
