/*
 * generated by Xtext 2.20.0
 */
package org.xtext.ftl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.ftl.ui.internal.FtlActivator;

public class FTLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FtlActivator.getInstance().getInjector("org.xtext.ftl.FTL");
	}

}
