/*
 * generated by Xtext 2.20.0
 */
package org.xtext.ftl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.ftl.parser.antlr.internal.InternalFTLParser;
import org.xtext.ftl.services.FTLGrammarAccess;

public class FTLParser extends AbstractAntlrParser {

	@Inject
	private FTLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFTLParser createParser(XtextTokenStream stream) {
		return new InternalFTLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public FTLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FTLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
