/*
 * generated by Xtext 2.20.0
 */
package org.xtext.ftl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FTLStandaloneSetup extends FTLStandaloneSetupGenerated {

	public static void doSetup() {
		new FTLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
